use_frameworks!

target 'SwiftyConstraints_Example' do
  pod 'SwiftyConstraints', :path => '../'

  target 'SwiftyConstraints_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
